# The contents of this file are parsed and made available as
# via `site.*`. So for example, {{ site.title }} can be used
# in a template to get the contents of the `title` key.
title: Hi, I’m Holy-Elie Scaide
subtitle: Software Developer Engineer
author: Holy-Elie Scaide

# Insert your disqus shortname
#disqus:
#    shortname:
