sculpin_content_types:
    posts:
        permalink: blog/:year/:month/:day/:filename/
sculpin_markdown:
    parser_class: Sculpin\Bundle\MarkdownBundle\PhpMarkdownExtraParser

# To disable posts (e.g., if you aren't planning on having any posts and Sculpin's watch mode complains):
#sculpin_content_types:
#    posts:
#        enabled: false
